import { FeedItem } from "./feeds";

export const MOCK_ITEMS: FeedItem[] = [
  // ── Security Critical ────────────────────────────────────────────
  {
    id: "mock-sc-1",
    title: "BSI warnt vor kritischer Schwachstelle in Microsoft Exchange Server",
    link: "https://www.bsi.bund.de",
    pubDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    description: "Das BSI hat eine Sicherheitswarnung für Microsoft Exchange Server herausgegeben. Betroffen sind die Versionen 2019, 2016 und 2013. Administratoren wird dringend empfohlen, den verfügbaren Patch umgehend einzuspielen.",
    source: "BSI Warnungen",
    category: "security_critical",
    language: "de",
  },
  {
    id: "mock-sc-2",
    title: "CERT-Bund: Kritische Schwachstellen in Cisco IOS XE aktiv ausgenutzt",
    link: "https://wid.cert-bund.de",
    pubDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    description: "CVE-2025-20188 und CVE-2025-20124 werden aktiv für Angriffe auf Netzwerkinfrastruktur genutzt. CERT-Bund empfiehlt sofortiges Patching. CVSS-Score: 9.8 (kritisch).",
    source: "CERT-Bund",
    category: "security_critical",
    language: "de",
  },
  {
    id: "mock-sc-3",
    title: "CISA adds 3 Known Exploited Vulnerabilities to Catalog",
    link: "https://www.cisa.gov",
    pubDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    description: "CISA has added three new vulnerabilities to its Known Exploited Vulnerabilities Catalog, based on evidence of active exploitation: CVE-2025-30406 (Ivanti), CVE-2025-29824 (Windows CLFS), CVE-2025-31201 (Apple iOS).",
    source: "CISA Alerts",
    category: "security_critical",
    language: "en",
  },
  {
    id: "mock-sc-4",
    title: "BSI Pressemitteilung: Lagebericht IT-Sicherheit in Deutschland 2025",
    link: "https://www.bsi.bund.de",
    pubDate: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    description: "Die Bedrohungslage im Cyberraum bleibt auf hohem Niveau. Ransomware, DDoS und Supply-Chain-Angriffe dominierten das Jahr 2025. Besonders kritische Infrastrukturen sind verstärkt Ziel von Angriffen.",
    source: "BSI Presse",
    category: "security_critical",
    language: "de",
  },
  {
    id: "mock-sc-5",
    title: "Zero-Day in FortiGate VPN wird für Angriffe auf Behörden genutzt",
    link: "https://www.bsi.bund.de",
    pubDate: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    description: "Eine ungepatchte Schwachstelle in Fortinet FortiGate wird aktiv für Angriffe auf Regierungseinrichtungen in Europa ausgenutzt. Das BSI koordiniert die Incident Response.",
    source: "BSI Warnungen",
    category: "security_critical",
    language: "de",
  },

  // ── Security News ─────────────────────────────────────────────────
  {
    id: "mock-sn-1",
    title: "Heise Security: NIS2-Umsetzung in deutschen Behörden schleppend",
    link: "https://www.heise.de/security",
    pubDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    description: "Viele Bundesbehörden haben die NIS2-Anforderungen noch nicht vollständig umgesetzt. Experten warnen vor erheblichen Compliance-Lücken und fordern mehr Ressourcen für CISO-Stellen.",
    source: "Heise Security",
    category: "security_news",
    language: "de",
  },
  {
    id: "mock-sn-2",
    title: "ENISA: New threat landscape for 2025 — AI-assisted attacks rising",
    link: "https://www.enisa.europa.eu",
    pubDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    description: "ENISA's annual threat landscape report highlights a 35% increase in AI-assisted phishing and deepfake-based social engineering attacks targeting European government institutions.",
    source: "ENISA Advisories",
    category: "security_news",
    language: "en",
  },
  {
    id: "mock-sn-3",
    title: "Krebs on Security: Inside the Botnet Targeting German Critical Infrastructure",
    link: "https://krebsonsecurity.com",
    pubDate: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    description: "An investigation reveals a sophisticated botnet with over 40,000 compromised endpoints targeting KRITIS sectors including energy, water, and government networks.",
    source: "Krebs on Security",
    category: "security_news",
    language: "en",
  },
  {
    id: "mock-sn-4",
    title: "Schneier: On the Security of Quantum-Resistant Algorithms in Government",
    link: "https://www.schneier.com",
    pubDate: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    description: "Post-quantum cryptography implementation timelines for government agencies need acceleration. NIST's recently finalized standards should be adopted in critical systems before 2027.",
    source: "Schneier on Security",
    category: "security_news",
    language: "en",
  },
  {
    id: "mock-sn-5",
    title: "Heise: Bundesbehörden sollen bis 2026 auf BIOS-Attestierung umstellen",
    link: "https://www.heise.de/security",
    pubDate: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    description: "Das BMI plant eine verbindliche Einführung von TPM 2.0-basierter BIOS-Attestierung für alle Bundesbehörden. Ziel ist der Schutz vor Firmware-Angriffen und Bootkits.",
    source: "Heise Security",
    category: "security_news",
    language: "de",
  },

  // ── Government IT ─────────────────────────────────────────────────
  {
    id: "mock-gi-1",
    title: "Golem: Portalverbund scheitert erneut an Interoperabilität der Länder",
    link: "https://www.golem.de",
    pubDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    description: "Der Nationale IT-Gipfel offenbarte tiefe Risse zwischen Bundes- und Landesbehörden bei der Umsetzung des Online-Zugangsgesetzes. Technische Schulden und fehlende Standards blockieren den Fortschritt.",
    source: "Golem Politik & Verwaltung",
    category: "government_it",
    language: "de",
  },
  {
    id: "mock-gi-2",
    title: "netzpolitik.org: Bundesregierung plant zentrales KI-Modell für die Verwaltung",
    link: "https://netzpolitik.org",
    pubDate: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    description: "Ein Referentenentwurf des BMI sieht ein souveränes, in Deutschland betriebenes Large Language Model für Bundesbehörden vor. Datenschutz und Transparenzanforderungen sollen verankert werden.",
    source: "Netzpolitik.org",
    category: "government_it",
    language: "de",
  },
  {
    id: "mock-gi-3",
    title: "Heise iX: Cloud-Strategie des Bundes — zwischen Souveränität und Pragmatismus",
    link: "https://www.heise.de/ix",
    pubDate: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    description: "Die Bundescloud-Strategie sieht künftig drei Kategorien vor: VS-GEHEIM-Verarbeitung on-premise, VS-NfD in zertifizierten deutschen Rechenzentren, und nicht-klassifiziertes bei EUCS-zertifizierten Anbietern.",
    source: "Heise iX",
    category: "government_it",
    language: "de",
  },
  {
    id: "mock-gi-4",
    title: "ZDNet: Open-Source-Offensive: Bund setzt verstärkt auf Open-Source-Software",
    link: "https://www.zdnet.de",
    pubDate: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    description: "Der Bundesbeauftragte für IT hat eine neue Richtlinie veröffentlicht, die Open-Source-Lösungen als Standard für neue IT-Projekte des Bundes vorschreibt. Ausnahmen bedürfen einer schriftlichen Begründung.",
    source: "ZDNet Deutschland",
    category: "government_it",
    language: "de",
  },
  {
    id: "mock-gi-5",
    title: "Golem: Digitale Identität — eID-Wallet geht in Pilotbetrieb",
    link: "https://www.golem.de",
    pubDate: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    description: "Die EUDI-Wallet-Pilotphase startet mit 10 Bundesbehörden und drei Bundesländern. Bis Ende 2026 sollen alle Verwaltungsleistungen mit der digitalen Identität nutzbar sein.",
    source: "Golem Politik & Verwaltung",
    category: "government_it",
    language: "de",
  },

  // ── EU Policy ─────────────────────────────────────────────────────
  {
    id: "mock-eu-1",
    title: "EU Commission: Cyber Resilience Act — Implementing Acts Published",
    link: "https://digital-strategy.ec.europa.eu",
    pubDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    description: "The European Commission has published implementing acts for the Cyber Resilience Act, specifying technical requirements for critical products. Manufacturers must comply by September 2027.",
    source: "EU Kommission Digital",
    category: "eu_policy",
    language: "en",
  },
  {
    id: "mock-eu-2",
    title: "ENISA: NIS2 Transposition — 8 Member States Still Behind Schedule",
    link: "https://www.enisa.europa.eu",
    pubDate: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    description: "ENISA's monitoring report reveals 8 EU member states have not yet fully transposed NIS2 Directive into national law. Infringement proceedings may follow for non-compliant states.",
    source: "ENISA News",
    category: "eu_policy",
    language: "en",
  },
  {
    id: "mock-eu-3",
    title: "EDPB: New Guidelines on AI Systems and GDPR Compliance",
    link: "https://edpb.europa.eu",
    pubDate: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    description: "The European Data Protection Board has adopted guidelines clarifying the intersection of the EU AI Act and GDPR, with specific provisions for government use of AI in decision-making processes.",
    source: "Europäischer Datenschutzausschuss",
    category: "eu_policy",
    language: "en",
  },
  {
    id: "mock-eu-4",
    title: "EU AI Act: Umsetzungsfristen für Hochrisiko-KI-Systeme in Behörden",
    link: "https://digital-strategy.ec.europa.eu",
    pubDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    description: "Für Behörden gelten besondere Transparenz- und Registrierungspflichten für KI-Systeme nach Art. 50 EU AI Act ab August 2026. Die Kommission hat Leitlinien für öffentliche Stellen veröffentlicht.",
    source: "EU Kommission Digital",
    category: "eu_policy",
    language: "en",
  },
  {
    id: "mock-eu-5",
    title: "European Health Data Space: Interoperability Standards Finalized",
    link: "https://digital-strategy.ec.europa.eu",
    pubDate: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    description: "The European Commission adopted implementing acts establishing technical specifications for the European Health Data Space, with implications for national health IT infrastructure.",
    source: "EU Kommission Digital",
    category: "eu_policy",
    language: "en",
  },

  // ── Tech Trends ───────────────────────────────────────────────────
  {
    id: "mock-tt-1",
    title: "MIT Technology Review: The race to build quantum-safe government networks",
    link: "https://www.technologyreview.com",
    pubDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    description: "Governments worldwide are racing to upgrade cryptographic infrastructure ahead of quantum computing milestones. Germany's BSI has published a roadmap targeting full post-quantum migration by 2030.",
    source: "MIT Technology Review",
    category: "tech_trends",
    language: "en",
  },
  {
    id: "mock-tt-2",
    title: "Heise Online: Open-Source KI für die Verwaltung — Chancen und Risiken",
    link: "https://www.heise.de",
    pubDate: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    description: "Behörden experimentieren mit lokalen Open-Source-Modellen wie Llama 3 und Mistral für interne Verwaltungsaufgaben. Datensouveränität spricht dafür, fehlende Enterprise-Reife dagegen.",
    source: "Heise Online",
    category: "tech_trends",
    language: "de",
  },
  {
    id: "mock-tt-3",
    title: "t3n: Warum die Public Cloud für Bundesbehörden besser wird",
    link: "https://t3n.de",
    pubDate: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    description: "AWS, Azure und Google Cloud investieren massiv in EU-Souveränitäts-Clouds mit deutschen Datentreuhändern. EUCS-Level-Hoch-Zertifizierungen könnten 2026 für Behördeneinsatz freigegeben werden.",
    source: "t3n",
    category: "tech_trends",
    language: "de",
  },
  {
    id: "mock-tt-4",
    title: "Wired: How Europe's Digital Infrastructure Plans Are Being Reshaped by Geopolitics",
    link: "https://www.wired.com",
    pubDate: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
    description: "Increasing transatlantic tensions are accelerating EU investments in independent digital infrastructure, from submarine cables to semiconductor fabs and cloud hyperscalers.",
    source: "Wired",
    category: "tech_trends",
    language: "en",
  },
  {
    id: "mock-tt-5",
    title: "Heise Online: DevSecOps in Bundesbehörden — wo stehen wir 2026?",
    link: "https://www.heise.de",
    pubDate: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    description: "Eine Umfrage unter 120 Bundesbehörden zeigt: 62% haben DevSecOps-Prozesse eingeführt, aber nur 23% setzen automatisierte Security-Scans in CI/CD-Pipelines konsequent ein.",
    source: "Heise Online",
    category: "tech_trends",
    language: "de",
  },

  // ── AI & Innovation ───────────────────────────────────────────────
  {
    id: "mock-ai-1",
    title: "The Verge: OpenAI's new o3-mini model can reason over classified documents",
    link: "https://www.theverge.com",
    pubDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    description: "OpenAI announced a government-specific deployment of o3-mini with enhanced security features, designed for classified environment operation — raising questions about data residency and oversight.",
    source: "The Verge – AI",
    category: "ai_innovation",
    language: "en",
  },
  {
    id: "mock-ai-2",
    title: "Golem KI: Bundesbehörden testen KI-gestützte Sachbearbeitung",
    link: "https://www.golem.de",
    pubDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    description: "Das Bundesamt für Migration und Flüchtlinge (BAMF) und das Finanzamt Bayern pilotieren KI-Systeme für die automatisierte Vorbescheidung. Erste Ergebnisse zeigen 40% Effizienzgewinn bei Standardfällen.",
    source: "Golem KI",
    category: "ai_innovation",
    language: "de",
  },
  {
    id: "mock-ai-3",
    title: "Heise KI: Multimodale Modelle in der Dokumentenverarbeitung für Behörden",
    link: "https://www.heise.de",
    pubDate: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    description: "Neue multimodale LLMs ermöglichen die automatische Verarbeitung von Scans, Handschriften und Formularen in Behörden. Pilotprojekte laufen im Bundesarchiv und beim Kraftfahrtbundesamt.",
    source: "Heise KI",
    category: "ai_innovation",
    language: "de",
  },
  {
    id: "mock-ai-4",
    title: "The Verge: EU AI Office begins monitoring high-risk AI deployments",
    link: "https://www.theverge.com",
    pubDate: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
    description: "The newly established EU AI Office has begun active monitoring of high-risk AI systems deployed by public authorities, with 34 systems already under review across member states.",
    source: "The Verge – AI",
    category: "ai_innovation",
    language: "en",
  },
  {
    id: "mock-ai-5",
    title: "Golem KI: Halluzinationen in Behörden-KI — Risiken und Gegenmaßnahmen",
    link: "https://www.golem.de",
    pubDate: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
    description: "Ein Gutachten des IT-Planungsrats warnt vor den Risiken von LLM-Halluzinationen in Verwaltungsentscheidungen und empfiehlt obligatorische Human-in-the-Loop-Verfahren sowie RAG-Architekturen.",
    source: "Golem KI",
    category: "ai_innovation",
    language: "de",
  },
];
