import { SocialPost } from "./social";

export const MOCK_SOCIAL: SocialPost[] = [
  {
    id: "ms-1",
    platform: "mastodon",
    author: "BSI Presse",
    handle: "bsi@social.bund.de",
    content: "⚠️ #BSI warnt vor aktiver Ausnutzung von CVE-2026-1234 in FortiGate VPN. Betriebene Systeme sollten umgehend gepatcht werden. Details im BSI-Sicherheitshinweis: wid.cert-bund.de #cybersecurity #infosec #KRITIS",
    link: "https://social.bund.de/@bsi",
    pubDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    boosts: 312,
    likes: 89,
    tags: ["bsi", "cybersecurity", "infosec", "kritis"],
    instance: "social.bund.de",
  },
  {
    id: "ms-2",
    platform: "bluesky",
    author: "Kevin Beaumont",
    handle: "gossithedog.bsky.social",
    content: "The FortiGate mass exploitation is real and large scale. Multiple government networks in Europe confirmed compromised. Patch or isolate immediately. Threat actor appears to be nation-state. #infosec #vulnerability",
    link: "https://bsky.app/profile/gossithedog.bsky.social",
    pubDate: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    boosts: 847,
    likes: 2341,
    tags: ["infosec", "vulnerability"],
  },
  {
    id: "ms-3",
    platform: "mastodon",
    author: "CERT-EU",
    handle: "certeu@social.network.europa.eu",
    content: "🔴 CERT-EU Security Advisory: Critical RCE in Ivanti Connect Secure (CVSS 9.9). All EU institutions urged to apply emergency patch immediately. No authentication required for exploitation. #cybersecurity #nis2",
    link: "https://cert.europa.eu",
    pubDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    boosts: 521,
    likes: 134,
    tags: ["cybersecurity", "nis2"],
    instance: "infosec.exchange",
  },
  {
    id: "ms-4",
    platform: "mastodon",
    author: "Netzpolitik",
    handle: "netzpolitik@chaos.social",
    content: "Das neue Bundesministerium für Digitalisierung hat erste Leitlinien zur KI-Nutzung in Bundesbehörden veröffentlicht. Datenschutz und Transparenzpflichten stehen im Vordergrund. #Digitalisierung #Verwaltungsdigitalisierung #OZG",
    link: "https://netzpolitik.org",
    pubDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    boosts: 203,
    likes: 445,
    tags: ["digitalisierung", "ozg"],
    instance: "chaos.social",
  },
  {
    id: "ms-5",
    platform: "bluesky",
    author: "Patch Tuesday Tracker",
    handle: "patchtuesday.bsky.social",
    content: "Microsoft June 2026 Patch Tuesday: 78 CVEs, 6 Critical, 2 zero-days actively exploited. CVE-2026-30190 (MSDT) and CVE-2026-26923 (AD CS) are top priority for enterprise environments. #PatchTuesday #cybersecurity",
    link: "https://bsky.app",
    pubDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    boosts: 1203,
    likes: 3891,
    tags: ["patchtuesday", "cybersecurity"],
  },
  {
    id: "ms-6",
    platform: "mastodon",
    author: "Digitalministerium Bund",
    handle: "bmds@social.bund.de",
    content: "📋 Start der öffentlichen Konsultation zur Fortschreibung der Nationalen Cloud-Strategie. Bis 31. Juli können sich Behörden, Unternehmen und Bürger:innen beteiligen. #CloudStrategie #Verwaltungsdigitalisierung #Bundescloud",
    link: "https://social.bund.de",
    pubDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    boosts: 87,
    likes: 156,
    tags: ["cloudstrategie", "verwaltungsdigitalisierung", "bundescloud"],
    instance: "social.bund.de",
  },
  {
    id: "ms-7",
    platform: "mastodon",
    author: "Heise Security",
    handle: "heisesecurity@mastodon.social",
    content: "Ransomware-Gruppe Cl0p nutzt neuen Zero-Day in MOVEit-Nachfolger aus. Bereits über 40 Unternehmen und Behörden in Deutschland betroffen. CERT-Bund koordiniert Incident Response. #Ransomware #KRITIS #infosec",
    link: "https://mastodon.social/@heisesecurity",
    pubDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    boosts: 634,
    likes: 287,
    tags: ["ransomware", "kritis", "infosec"],
    instance: "mastodon.social",
  },
  {
    id: "ms-8",
    platform: "bluesky",
    author: "EU Cybersecurity",
    handle: "eucybersec.bsky.social",
    content: "🇪🇺 ENISA publishes updated NIS2 implementation guidance for public authorities. Key changes: incident reporting timelines reduced to 24h initial notification, new supply chain security requirements. #NIS2 #ENISA #cybersecurity",
    link: "https://bsky.app",
    pubDate: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    boosts: 445,
    likes: 891,
    tags: ["nis2", "enisa", "cybersecurity"],
  },
  {
    id: "ms-9",
    platform: "mastodon",
    author: "IT-Planungsrat",
    handle: "itplanungsrat@social.bund.de",
    content: "🏛️ IT-Planungsrat beschließt einheitlichen Standard für digitale Identitäten in Behörden. Alle Bundesbehörden müssen bis 2027 auf die EUDI-Wallet-Infrastruktur umstellen. #eGovernment #DigitaleIdentität #OZG",
    link: "https://social.bund.de",
    pubDate: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    boosts: 156,
    likes: 312,
    tags: ["egovernment", "digitaleidentität", "ozg"],
    instance: "social.bund.de",
  },
  {
    id: "ms-10",
    platform: "mastodon",
    author: "MalwareMustDie",
    handle: "malwaremustdie@infosec.exchange",
    content: "New Emotet campaign targeting German Behörde with 'Steuerprüfung' lure. Macro-enabled XLSM dropper, C2 at [redacted]. BSI already notified. Block at perimeter immediately. IOCs: [thread] #malware #infosec #cybersecurity",
    link: "https://infosec.exchange/@malwaremustdie",
    pubDate: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    boosts: 891,
    likes: 423,
    tags: ["malware", "infosec", "cybersecurity"],
    instance: "infosec.exchange",
  },
  {
    id: "ms-11",
    platform: "bluesky",
    author: "Schneier on Security",
    handle: "schneier.bsky.social",
    content: "Post-quantum cryptography migration for government systems needs to start NOW, not in 2028. The 'harvest now, decrypt later' threat is real for classified data. NIST finalized standards are ready. No more excuses. #pqcrypto #cybersecurity",
    link: "https://bsky.app",
    pubDate: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    boosts: 2341,
    likes: 5678,
    tags: ["pqcrypto", "cybersecurity"],
  },
  {
    id: "ms-12",
    platform: "mastodon",
    author: "DSGVO-Portal",
    handle: "dsgvo@social.bund.de",
    content: "Neue Orientierungshilfe des BfDI: KI-gestützte Verwaltungsentscheidungen nach Art. 22 DSGVO. Behörden müssen bei vollautomatisierten Entscheidungen immer eine menschliche Überprüfung sicherstellen. #DSGVO #GDPR #KI #AIAct",
    link: "https://social.bund.de",
    pubDate: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    boosts: 234,
    likes: 567,
    tags: ["dsgvo", "gdpr", "ki", "aiact"],
    instance: "social.bund.de",
  },
];
